# Generated by Django 2.2.7 on 2020-05-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='totalCart',
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Ijebu-Ode, Ogun State, Nigeria', max_length=255),
        ),
    ]
