# Generated by Django 2.2.7 on 2020-04-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me', models.CharField(max_length=255)),
                ('myFriend', models.CharField(max_length=255)),
                ('chat', models.TextField(max_length=100000)),
            ],
        ),
        migrations.AlterField(
            model_name='msg',
            name='status',
            field=models.CharField(choices=[('r', 'read'), ('u', 'unread')], default='u', max_length=1),
        ),
    ]
