# Generated by Django 2.2.7 on 2020-04-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200423_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='date_added',
            field=models.DateField(default='2020-04-23'),
        ),
    ]
