# Generated by Django 2.2.7 on 2020-04-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('chat', models.TextField(max_length=100000)),
                ('timestamp', models.DateTimeField()),
                ('mode', models.CharField(default='receive', editable=False, max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='SendChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('chat', models.TextField(max_length=100000)),
                ('timestamp', models.DateTimeField()),
                ('mode', models.CharField(default='send', editable=False, max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
