# Generated by Django 2.2.7 on 2020-04-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20200423_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('chat', models.TextField(max_length=100000)),
                ('timestamp', models.DateTimeField()),
                ('mode', models.CharField(choices=[('s', 'send'), ('r', 'receive')], default='s', max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='ReceiveChat',
        ),
        migrations.DeleteModel(
            name='SendChat',
        ),
    ]
