# Generated by Django 2.2.7 on 2020-04-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20200423_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='key',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friend',
            name='date_added',
            field=models.DateField(default='2020-04-24'),
        ),
    ]
