# Generated by Django 2.2.7 on 2020-04-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20200424_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('a', 'accepted'), ('d', 'declined')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='friend',
            name='date_added',
            field=models.DateField(default='2020-04-25'),
        ),
    ]
