# Generated by Django 2.2.7 on 2020-04-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20200425_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='date_added',
            new_name='timestamp',
        ),
    ]
