# Generated by Django 2.2.7 on 2020-04-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20200425_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='mode',
            field=models.CharField(choices=[('r', 'received'), ('s', 'sent')], default='s', max_length=1),
        ),
    ]
