# Generated by Django 2.2.7 on 2020-05-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_contact_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='friend',
            name='timestamp',
            field=models.DateField(default='2020-05-02'),
        ),
    ]
