# Generated by Django 2.2.7 on 2020-05-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_auto_20200502_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mode',
            field=models.CharField(choices=[('s', 'sent'), ('r', 'received')], default='s', max_length=1),
        ),
        migrations.AlterField(
            model_name='friend',
            name='timestamp',
            field=models.DateField(default='2020-05-03'),
        ),
    ]
