# Generated by Django 2.2.7 on 2020-05-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='key',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.AddField(
            model_name='notification',
            name='body',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='notification',
            name='contact',
            field=models.EmailField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact',
            field=models.EmailField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
