# Generated by Django 2.2.7 on 2020-05-10 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_auto_20200510_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 1, 56, 53, 967269)),
        ),
    ]
