# Generated by Django 2.2.7 on 2020-05-10 00:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_notification_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 0, 57, 32, 779044, tzinfo=utc)),
        ),
    ]
