# Generated by Django 2.2.7 on 2020-05-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_auto_20200510_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('r', 'read'), ('u', 'unread')], default='u', max_length=1),
        ),
    ]
